### ISSUE TITLE
Change default branch from heroku to main

### ISSUE THREAD

**Issue by goodsign** [Uscreen-video/credman#7]
We have this code now:

```
class Diff < Dry::CLI::Command
  desc "Show credentials diff between given branch (heroku by default) and current changes"

  argument :branch, type: :string, default: "heroku", required: false
```

I don't think `heroku` is a popular default branch. Will be `main` in 99% cases. So what I'd suggest is changing this here to `main` + giving a way to set a project-wide default (to allow Uscreen folks to default to `heroku`)

**Comment by Riddlerrr** [comment]
@goodsign Yep, I've already created the issue about that: https://github.com/Uscreen-video/credman/issues/5
